### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by for-just-we** [ucsb-seclab/syml#2]
Hi, author. I'm interested in your work. But I don't see dataset.  Would you mind sharing on Github. Thank you very much if you can

**Comment by lucy112750** [comment]
Hi, author. I'm interested in your work. Would you mind sharing on Github. Thank you very much！

**Comment by lucy112750** [comment]
Hi,author.I have a problem about syml when  I retry the work.
This is my command:
python run.py --filename /home/sfb/syml/work/test_data/CADET_00001 --pov /home/sfb/syml/work/test_data/POV_00000.xml --analyse

The above command results the following error:

INFO    | 2022-01-05 14:06:50,821 | syml.tracing.tracer | Starting to trace binary CADET_00001 with input POV_00000.xml
ERROR   | 2022-01-05 14:06:52,868 | syml | POV_00000.xml@CADET_00001 terminated with exception 'AttributeError' - ("'angrProjectAnalyzer' object has no attribute 'scout_bow'",)
Traceback (most recent call last):
  File "run.py", line 72, in <module>
    tracer.run(write_callback=write_callback)
  File "/home/sfb/syml/work/syml/tracing/tracer.py", line 59, in run
    self._run(target, r, write_callback)
  File "/home/sfb/syml/work/syml/tracing/tracer.py", line 70, in _run
    project = proj_bow.fire(base_addr=None)
  File "/home/sfb/syml/work/syml/tracing/utils/__init__.py", line 37, in fire
    if self.scout_bow is not None:
AttributeError: 'angrProjectAnalyzer' object has no attribute 'scout_bow'


Could you please give me some advice?Thank you very much!

**Comment by ruaronicola** [comment]
Closing this after adding a README with some details on the project. (The attribute error posted above was solved by using a different version of angr and archr. It happens because the archr package was [recently rewritten](https://github.com/angr/archr/blob/master/archr/analyzers/angr_project.py#L62) and that functionality was renamed to "analyzers'')
