### ISSUE TITLE
README creation and walkthrough of tool usage on CGC binary

### ISSUE THREAD

**Issue by Btraube** [ucsb-seclab/syml#3]
Hello!

I understand that some time has gone by where this project has not been touched upon, but I was wondering if there could be a creation of a README document for this project. Something that would help with guiding users on execution, setup, and optimization using built in tool features?

A walkthrough of command line inputs when using the tool on one of the tested CGC binaries would be incredibly helpful for understanding the tool's usage and capabilities! 

Please let me know thoughts on this and I would be glad to offer any help if needed!

**Comment by ruaronicola** [comment]
Hi there! I just updated the repo with some details on how to run the project, where to find the CGC binaries and seeds, and some known issues. Thanks for the suggestion! :)
